/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppQuestionsRouteImport } from './routes/_app/questions'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'
import { Route as AppInterviewsIndexRouteImport } from './routes/_app/interviews/index'
import { Route as AppInterviewsSessionIdRouteImport } from './routes/_app/interviews/$sessionId'
import { Route as AppPracticeIndexRouteImport } from './routes/_app/practice/index'
import { Route as AppPracticeSessionIdRouteImport } from './routes/_app/practice/$sessionId'
import { Route as AppRolesRoleIdRouteImport } from './routes/_app/roles/$roleId'
import { Route as AppSetsSetIdRouteImport } from './routes/_app/sets/$setId'
import { Route as AppWorkplaceCasesIndexRouteImport } from './routes/_app/workplace-cases/index'
import { Route as AppWorkplaceCasesSessionsSessionIdRouteImport } from './routes/_app/workplace-cases/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInterviewsSessionIdRoute = AppInterviewsSessionIdRouteImport.update({
  id: '/interviews/$sessionId',
  path: '/interviews/$sessionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPracticeSessionIdRoute = AppPracticeSessionIdRouteImport.update({
  id: '/practice/$sessionId',
  path: '/practice/$sessionId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSetsSetIdRoute = AppSetsSetIdRouteImport.update({
  id: '/sets/$setId',
  path: '/sets/$setId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkplaceCasesIndexRoute = AppWorkplaceCasesIndexRouteImport.update({
  id: '/workplace-cases/',
  path: '/workplace-cases/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkplaceCasesSessionsSessionIdRoute =
  AppWorkplaceCasesSessionsSessionIdRouteImport.update({
    id: '/workplace-cases/sessions/$sessionId',
    path: '/workplace-cases/sessions/$sessionId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/questions': typeof AppQuestionsRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/interviews/$sessionId': typeof AppInterviewsSessionIdRoute
  '/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/sets/$setId': typeof AppSetsSetIdRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/interviews/': typeof AppInterviewsIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/workplace-cases/': typeof AppWorkplaceCasesIndexRoute
  '/workplace-cases/sessions/$sessionId': typeof AppWorkplaceCasesSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/questions': typeof AppQuestionsRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/interviews/$sessionId': typeof AppInterviewsSessionIdRoute
  '/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/sets/$setId': typeof AppSetsSetIdRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/interviews': typeof AppInterviewsIndexRoute
  '/practice': typeof AppPracticeIndexRoute
  '/workplace-cases': typeof AppWorkplaceCasesIndexRoute
  '/workplace-cases/sessions/$sessionId': typeof AppWorkplaceCasesSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/questions': typeof AppQuestionsRoute
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/interviews/$sessionId': typeof AppInterviewsSessionIdRoute
  '/_app/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/_app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/_app/sets/$setId': typeof AppSetsSetIdRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/interviews/': typeof AppInterviewsIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/workplace-cases/': typeof AppWorkplaceCasesIndexRoute
  '/_app/workplace-cases/sessions/$sessionId': typeof AppWorkplaceCasesSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/questions'
    | '/companies/$companyId'
    | '/interviews/$sessionId'
    | '/practice/$sessionId'
    | '/roles/$roleId'
    | '/sets/$setId'
    | '/companies/'
    | '/interviews/'
    | '/practice/'
    | '/workplace-cases/'
    | '/workplace-cases/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/questions'
    | '/companies/$companyId'
    | '/interviews/$sessionId'
    | '/practice/$sessionId'
    | '/roles/$roleId'
    | '/sets/$setId'
    | '/companies'
    | '/interviews'
    | '/practice'
    | '/workplace-cases'
    | '/workplace-cases/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/questions'
    | '/_app/companies/$companyId'
    | '/_app/interviews/$sessionId'
    | '/_app/practice/$sessionId'
    | '/_app/roles/$roleId'
    | '/_app/sets/$setId'
    | '/_app/companies/'
    | '/_app/interviews/'
    | '/_app/practice/'
    | '/_app/workplace-cases/'
    | '/_app/workplace-cases/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/questions': {
      id: '/_app/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/interviews/': {
      id: '/_app/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/interviews/$sessionId': {
      id: '/_app/interviews/$sessionId'
      path: '/interviews/$sessionId'
      fullPath: '/interviews/$sessionId'
      preLoaderRoute: typeof AppInterviewsSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/practice/$sessionId': {
      id: '/_app/practice/$sessionId'
      path: '/practice/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof AppPracticeSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/$roleId': {
      id: '/_app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sets/$setId': {
      id: '/_app/sets/$setId'
      path: '/sets/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof AppSetsSetIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workplace-cases/': {
      id: '/_app/workplace-cases/'
      path: '/workplace-cases'
      fullPath: '/workplace-cases/'
      preLoaderRoute: typeof AppWorkplaceCasesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/workplace-cases/sessions/$sessionId': {
      id: '/_app/workplace-cases/sessions/$sessionId'
      path: '/workplace-cases/sessions/$sessionId'
      fullPath: '/workplace-cases/sessions/$sessionId'
      preLoaderRoute: typeof AppWorkplaceCasesSessionsSessionIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppInterviewsSessionIdRoute: typeof AppInterviewsSessionIdRoute
  AppPracticeSessionIdRoute: typeof AppPracticeSessionIdRoute
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppSetsSetIdRoute: typeof AppSetsSetIdRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppWorkplaceCasesIndexRoute: typeof AppWorkplaceCasesIndexRoute
  AppWorkplaceCasesSessionsSessionIdRoute: typeof AppWorkplaceCasesSessionsSessionIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppInterviewsSessionIdRoute: AppInterviewsSessionIdRoute,
  AppPracticeSessionIdRoute: AppPracticeSessionIdRoute,
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppSetsSetIdRoute: AppSetsSetIdRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppWorkplaceCasesIndexRoute: AppWorkplaceCasesIndexRoute,
  AppWorkplaceCasesSessionsSessionIdRoute:
    AppWorkplaceCasesSessionsSessionIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
